### ISSUE TITLE
dispathes for scrolling through desktops

### ISSUE THREAD

**Issue by mariospicross** [levnikmyskin/hyprland-virtual-desktops#1]
i would love to be able to cycle through desktops by pressing an arrow key or something and it would go to the next or previous desktop, allowing you to cycle through them. :D

**Comment by levnikmyskin** [comment]
Hey! Yep, that sounds like an easy to enough feature to implement. In these days I'm working on a new version of this plugin, with several enhancements. I will include this one too :)

**Comment by mariospicross** [comment]
thanks a ton! :D

**Comment by levnikmyskin** [comment]
This is implemented in new release. Closing issue.
