### ISSUE TITLE
focusmonitor bug

### ISSUE THREAD

**Issue by LaptopDev** [levnikmyskin/hyprland-virtual-desktops#10]
in my config I have 
```
bind = $mainMod, h, focusmonitor, 0
bind = $mainMod, l, focusmonitor, 1
```
With only 2 monitors, when 2 clients are on screen 2 on vdesk1, when I try moving to screen 1 (monitor id 0 according to hyprland), it instead moves focus to the leftward client sharing the screen 2 workspace.

When the clients are fullscreened on screen 2, the same behavior occurs, with the other client being focused, and this time fullscreened. 

Is there a way to move from any focused client on screen 2 to screen 1, so that the expected behavior for focusing between monitors works as it should?

**Comment by levnikmyskin** [comment]
Hi,
this does not seem related to this plugin, but rather to hyprland itself
