### ISSUE TITLE
Feature request: more relative motion

### ISSUE THREAD

**Issue by SamueleFacenda** [levnikmyskin/hyprland-virtual-desktops#13]
I would love to be able to go to the previous (number -1) desk and also to move my windows to the next/previous workspace.

Also the dispatchers name confused me, referring to next as the number+1 but previous as the latest visited and not the number-1. I will suggest to change the prevdesk dispatcher name to something like `lastdesk` or so.

**Comment by levnikmyskin** [comment]
Hi, can you check the PR https://github.com/levnikmyskin/hyprland-virtual-desktops/pull/14 ?

Code compiles but I haven't tested it yet

**Comment by SamueleFacenda** [comment]
Tested and it works!
Just a point, imo will be better for consistency to have something like `prevdesk`/`nextdesk` that don't cycles and `cyclevdesk`/`inversecyclevdesk`(?) that cycles (like prevdesk in this implementation), or a configuration setting to switch on/off this behaviour.

**Comment by levnikmyskin** [comment]
Thanks for your suggestion. Yes I was already thinking about including something like that. Probably I'll add another config variable, something like `backwardcycle`

**Comment by levnikmyskin** [comment]
Hi again. I have pushed some changes. I added the `backcyclevdesks`, which can now be paired with `cyclevdesks` for backward/forward cycling. Would you have time to test everything works? These days I'm mostly committing from another computer where I don't have hyprland configured

**Comment by SamueleFacenda** [comment]
Tested just now, everything works fine.

**Comment by levnikmyskin** [comment]
Thank you very much!
