### ISSUE TITLE
FEATURE: KDE's Activity

### ISSUE THREAD

**Issue by fedoranvar** [levnikmyskin/hyprland-virtual-desktops#15]
Good day to you!

is there any plans for implementing KDE's Activity feature or maybe ability to use it with external tool?

like, 

```sh
plugin {

activities {
    default { 
          virtual-desktops 1:coding, 2:internet, 3:mail and chats 
         cycleworkspaces = 1
          rememberlayout = size
          notifyinit = 0
          verbose_logging = 0
      }
    job { 
          virtual-desktops 1:coding, 2:internet, 3:mail and chats 
      }
  }
}
```

```bash
hyprctl dispatch activity job
```

thank you!

**Comment by levnikmyskin** [comment]
Hi!
I think that would be pretty cool, but probably something that another plugin should implement. It's not a feature concerning virtual desktops :)

**Comment by fedoranvar** [comment]
you're right. will dig further
