### ISSUE TITLE
FEATURE: Ability to get parsed list of virtual desktops via dispatcher

### ISSUE THREAD

**Issue by fedoranvar** [levnikmyskin/hyprland-virtual-desktops#16]
Good day to you!

is there  any ability to get parsed list of virtual desktops  via dispatcher?

usecase: jumping between desktops via fuzzy selector

```bash
hyprctl vdesks -j | rofi -dmenu
```

thank you!

**Comment by levnikmyskin** [comment]
Hello again!
So, I went looking at Hyprland's code again and, as far as I can tell, there's no way of printing via hyprctl for a plugin. This issue should be raised in Hyprland's repo, and see what vaxry thinks about this :)

**Comment by fedoranvar** [comment]
how to describe issue on Hyprland's repo?

"Ability print  plugin's runtime info"?

**Comment by levnikmyskin** [comment]
No, not really. This is more related to the ability of printing anything at all from an hyprctl dispatcher: this is impossible for plugins and hyprland code itself, as far as I can tell.

So, best thing would probably be something like "ability for plugins to print from hyprctl dispatchers" or "allow plugins to print to stdout from hyprctl dispatchers"

**Comment by fedoranvar** [comment]
@levnikmyskin 
vaxry had implemented some changes.
is it enough for this feature?

**Comment by levnikmyskin** [comment]
Hi,
Yes that is everything I need. I'll update you here on this ticket when I implement the feature. Maybe this weekend :)

**Comment by levnikmyskin** [comment]
Hey, 
just to give you an update: I didn't forget about this issue. It's just that Hyprland's implementation in v 0.35 was incomplete for this to work.
I already pushed (and vaxry merged) the changes upstream, so we will have this feature in 0.36 :)
