### ISSUE TITLE
FEATURE: Dispatcher `movetolastdesk` and `silently`

### ISSUE THREAD

**Issue by fedoranvar** [levnikmyskin/hyprland-virtual-desktops#17]
Good day to you!

suggestion for dispatcher's `movetolastdesk` and  `movetolastdesksilent`

Thank you!

**Comment by levnikmyskin** [comment]
https://github.com/levnikmyskin/hyprland-virtual-desktops/pull/18

Implemented here, feel welcome to test it if you have time
