### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by MysticBytes786** [levnikmyskin/hyprland-virtual-desktops#21]
I think it's due to the changes in syntax for plugins interacting with _Hyprland_ API.

**Comment by levnikmyskin** [comment]
Hi, I don't support mid-release commits in Hyprland in this plugin. This will be fixed when Hyprland releases the new hyprlang thing in the next 0.36.  
If you fix the build though, feel free to open a PR :)

**Comment by levnikmyskin** [comment]
if you want, you can try the PR already. I'll probably merge it in 4/5 hours, maybe a little more

**Comment by MysticBytes786** [comment]
I was planning to work on it after my exams, but you guys are shipping fast! Great work.
