### ISSUE TITLE
Help regarding NixOS

### ISSUE THREAD

**Issue by djelenc** [levnikmyskin/hyprland-virtual-desktops#28]
Thank your for this nice plugin. I'm struggling to integrate it into my NixOS config. A few questions:

- The README says  to point the flake to `hyprland-virtual-desktops.url = "github:wiillou/hyprland-virtual-desktops";`. Should I not point it to `hyprland-virtual-desktops.url = "github:levnikmyskin/hyprland-virtual-desktops";` instead?
- I would really appreciate how to move the configuration into a separate module as suggested in the README. In my case, I'm using home-manager where I was configuring hyprland before and would like to put all this plugin-related config there.

Also pinging @wiillou, since they contributed the initial NixOS config. All the best!

**Comment by levnikmyskin** [comment]
Hey! Definitely, you should point it to this repo and not willou's fork. We might have missed that!  (I have already updated this)
Regarding the NixOS specific stuff, I'm sure willou can help you better than I can :)

**Comment by wiillou** [comment]
Hello, thanks for pointing that out, made a PR for it

**Comment by wiillou** [comment]
lol, @levnikmyskin got to it before me, and yes i would be willing to help

**Comment by wiillou** [comment]
to split up the plugin related config to a specific file, you can use the relative path to the file in your homeConfigurations modules. here is an example
```
homeConfigurations = {
      "username@hostname" = home-manager.lib.homeManagerConfiguration {
        pkgs = inputs.nixpkgs.legacyPackages.x86_64-linux;
        extraSpecialArgs = {inherit inputs outputs;}; # Not sure if this is needed, i just use it
        modules = [ 
          ./path/to/file.nix
        ];
      };
```
 where `./path/to/file.nix` would contain something like:
```
{pkgs, inputs, ...}: {
  wayland.windowManager.hyprland = {
     enable = true;
     package = inputs.hyprland.packages.${pkgs.system}.hyprland;
     plugins = [
       hyprland-virtual-desktops.packages.${pkgs.system}.virtual-desktops
     ];
     extraConfig = builtins.readFile ./files/hyprland.conf; # or a different method to manage your hyprland config via HM
   };
  # ... the rest of your hyprland-realated configuration
 }
```

**Comment by djelenc** [comment]
Thank you for all the pointers @wiillou. However, I am still unable to get it working. It seems I cannot reference inputs (and outputs) from within the `nixosConfiguration` section. I have my configs online, so this is my flake file [here.](https://github.com/djelenc/.dotfiles/blob/65ece505434ed3c87c9315abd183325ad618bf88/flake.nix) The commands in questions are on line 27:

```nix
# ... omitted ...
nixosConfigurations = {
      idea = lib.nixosSystem {
        specialArgs = {inherit inputs outputs;}; 
      	modules = [ 
	  # sys
          ./idea/configuration.nix 

          # userland
          home-manager.nixosModules.home-manager {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.david = import ./idea/home.nix;
          }
        ];
      };
    };
```

I seems the `inherit` bit is required, since if I omit it, I get an error in the [`home.nix` file](https://github.com/djelenc/.dotfiles/blob/65ece505434ed3c87c9315abd183325ad618bf88/idea/home.nix), in particular it says `error: attribute 'hyprland-virtual-desktops' missing`. 

(I apologize: all of this is nixos/home-manager/flake specific, and not intended for for this project, but hopefully a potential solution might be interesting for someone else too.)

**Comment by wiillou** [comment]
> Thank you for all the pointers @wiillou. However, I am still unable to get it working. It seems I cannot reference inputs (and outputs) from within the `nixosConfiguration` section. (My configuration is slightly different than yours, but the error regarding inputs and outputs is the same in both cases.) I have my configs online, so this is my flake file [here.](https://github.com/djelenc/.dotfiles/blob/65ece505434ed3c87c9315abd183325ad618bf88/flake.nix) The commands in questions are on line 27, excerpt below.
> 
> ```nix
> # ... omitted ...
> nixosConfigurations = {
>       idea = lib.nixosSystem {
>         specialArgs = {inherit inputs outputs;}; 
>       	modules = [ 
> 	  # sys
>           ./idea/configuration.nix 
> 
>           # userland
>           home-manager.nixosModules.home-manager {
>             home-manager.useGlobalPkgs = true;
>             home-manager.useUserPackages = true;
>             home-manager.users.david = import ./idea/home.nix;
>           }
>         ];
>       };
>     };
> ```
> 
> I seems the `inherit` bit is required, since if I omit it, I get an error in the [`home.nix` file](https://github.com/djelenc/.dotfiles/blob/65ece505434ed3c87c9315abd183325ad618bf88/idea/home.nix), in particular it says `error: attribute 'hyprland-virtual-desktops' missing`. 
> 
> (I apologize: all of this is nixos/home-manager/flake specific, and not intended for for this project, but hopefully a potential solution might be interesting for someone else too.)

ah, im not exactly familiar with using it as a nixos module (i use a flake output). i will take a look at your configuration.

**Comment by wiillou** [comment]
@djelenc i think you have done it right, just add an imports section in your home.nix file that points to the file with your hyprland plugin configuration in. e.g add:

`home.nix`
```
# snip
  imports = [
    ./hyprland-configuration.nix
  ];
# snip
  ```
  
  where `hyprland-configuration.nix` contains:
  ```
  { inputs, pkgs, ... }:
  {
    wayland.windowManager.hyprland = {
      enable = true;
      # package = pkgs.hyprland;
      package = inputs.hyprland.packages.${pkgs.system}.hyprland;
      xwayland.enable = true;
      systemd.enable = false;

      plugins = [
        hyprland-virtual-desktops.packages.${pkgs.system}.virtual-desktops
      ];

      extraConfig = lib.fileContents ./hyprland.conf;
    };
  }
  ```

**Comment by djelenc** [comment]
Thank you. I did as suggested, but I'm stuck at the same place. I crated `hyprland-configuration.nix` file and moved the hyprland commands into it; [here's the file.](https://github.com/djelenc/.dotfiles/blob/3ed073544668466e55753e65113e68867c94b4a2/idea/hyprland-configuration.nix)

(And of course, I added the `imports` attribute into `home.nix` that points to the said file.)

The error remains the same: when building and switching, it says: `error: attribute 'hyprland-virtual-desktops' missing`. 

My nixos beginners logic has me believed I have to pass the reference to the `hyprland-virtual-desktops` flake into `home.nix` (and then `hyprland-configuration.nix`) somehow. Just do not know how.

**Comment by wiillou** [comment]
ah i see your mistake, ill fix it now @djelenc

**Comment by wiillou** [comment]
honestly, i have no idea how the nixos module for this works. i have no idea how to pass inputs down.

**Comment by wiillou** [comment]
oh wow, i just re-wrote your configuration using my schema that works perfectly fine usually, and it still doesn't work. very odd

**Comment by wiillou** [comment]
okay, i have a different error now, and i have got it to successfully build when using a flake entrypoint

**Comment by djelenc** [comment]
Thank you @wiillou for all the help. I finally got it working. I shall describe the solution in a day or two, but basically I had to rework my nixos and home-manager config a bit.

**Comment by wiillou** [comment]
> Thank you @wiillou for all the help. I finally got it working. I shall describe the solution in a day or two, but basically I had to rework my nixos and home-manager config a bit.

awesome!

**Comment by wiillou** [comment]
@levnikmyskin i would be happy to update the documentation with a few other ways of using the plugin via nix

**Comment by levnikmyskin** [comment]
sure @wiillou, that sounds great! Feel free to open a PR

**Comment by wiillou** [comment]
ill probably wait until the solution is posted so i can get a working configuration using the nixos module way of doing it

**Comment by djelenc** [comment]
So, this is what I've done; my entire config is [accessible here.](https://github.com/djelenc/.dotfiles)

1. This is my `flake.nix`.
    ```nix
    {
      inputs = {
        nixpkgs.url = "nixpkgs/nixos-unstable";

        home-manager = {
          url = "github:nix-community/home-manager/master";
          inputs.nixpkgs.follows = "nixpkgs";
        };

        hyprland = {
          url = "github:hyprwm/Hyprland";
          follows = "hyprland-virtual-desktops/hyprland"; 
        };
        hyprland-virtual-desktops.url = "github:levnikmyskin/hyprland-virtual-desktops";
      };

      # named the attribute set as inputs with '@ inputs' syntax
      outputs = { self, nixpkgs, home-manager, hyprland-virtual-desktops, ... } @ inputs : 
      let
        lib = nixpkgs.lib;
        system = "x86_64-linux";
        pkgs = nixpkgs.legacyPackages.${system};
      in {
        nixosConfigurations = {
          idea = lib.nixosSystem {
            # added this attribute
            specialArgs = { inherit inputs; };
            modules = [ 
              ./idea/configuration.nix 
              # changed the import below
              inputs.home-manager.nixosModules.default
            ];
          };
        };
      };
    ```

    Changes:
    - Named the attribute set `outputs = { self, nixpkgs, home-manager, hyprland-virtual-desktops, ... } @ inputs :` using the `@ inputs` 
    - Added the attribute name `specialArgs = { inherit inputs; };`
    - Changed the `modules` so that now I do not directly import `home.nix` but I import it through `configuration.nix` as shown next 
    
 2. Modified `configuration.nix` 
    ```nix
    { config, inputs, pkgs, lib, ... }:
    {
      imports = [ 
        ./hardware-configuration.nix
        inputs.home-manager.nixosModules.default # this was added
      ];

      # snip

      # this snippet (functionally) was previously in flake.nix
      home-manager = {
        useGlobalPkgs = true;
        useUserPackages = true;
        extraSpecialArgs = { inherit inputs; };
        users = {
          "david" = import ./home.nix;
        };
      };
    }
    ```
    Changes:
    - Now I import `inputs.home-manager.nixosModules.default`
    - I added the attribute set for `home-manager` within which I import the home manager file `home.nix`
3. Finally, `home.nix`
    ```nix
    { config, inputs, pkgs, lib, ... } : # added the inputs argument
    {
      # snip

      wayland.windowManager.hyprland = {
        enable = true;
        package = inputs.hyprland.packages.${pkgs.system}.hyprland;
        xwayland.enable = true;
        systemd.enable = false;

        plugins = [
          # prefixed the plugin name with inputs.
          inputs.hyprland-virtual-desktops.packages.${pkgs.system}.virtual-desktops
        ];

        extraConfig = lib.fileContents ./hyprland.conf;
      };
    }
    ```

**Comment by wiillou** [comment]
well done!

**Comment by djelenc** [comment]
Just to add: step 2 is not really related to this plugin -- it is just a way to configure home manager. 

The key part was, in step 1, naming the attribute set with `@ inputs` so that it gets passed down to imported modules, and setting the `specialArgs` keyword and then, in step 3, prefixing the plugin name with `inputs`.

**Comment by mjund** [comment]
i got the following problem: 

failed to load the following plugins: 
/nix/store/xyz-virtual-desktops-2.2.1/lib/libvirtual-desktops.so 

this is my config : 
{  inputs, pkgs, ... }: 
{
  wayland.windowManager.hyprland = {
              enable = true;
              package = inputs.hyprland.packages.${pkgs.system}.hyprland;
              xwayland.enable = true;
              systemd.enable = true;
              plugins = [
                # inputs.hyprland-virtual-desktops.packages.${pkgs.system}.virtual-desktops
              ];
              # extraConfig is a string that becomes hyprland.conf
              extraConfig = ''
                 stickyrule = class:^(kittysticky)$,3
                 stickyrule = title:thunderbird,mail

                 plugin {
                     virtual-desktops {
                         names = 1:coding, 2:internet, 3:mail and chats 
                         cycleworkspaces = 1
                         rememberlayout = size
                         notifyinit = 0
                         verbose_logging = 0
                     }
                 }
              '' + ''
                # your other configuration for hyprland
              '' +  builtins.readFile ./hyprland.conf ;
   };
}


nixos compile hyprland and the plugin with no problem but hyprland can't load the the plugin

**Comment by wiillou** [comment]
> i got the following problem: 
> 
> failed to load the following plugins: 
> /nix/store/xyz-virtual-desktops-2.2.1/lib/libvirtual-desktops.so 
> 

hello, which version of hyprland are you using?

**Comment by levnikmyskin** [comment]
Hyprland has just been updated to version 0.40.0.
This plugin has also now been adapted to the new changes. @wiillou could you take care of updating the nixos build? :pray:

**Comment by wiillou** [comment]
> Hyprland has just been updated to version 0.40.0.
> This plugin has also now been adapted to the new changes. @wiillou could you take care of updating the nixos build? :pray: 

yes of course, let me get on my laptop :)

**Comment by wiillou** [comment]
![image](https://github.com/levnikmyskin/hyprland-virtual-desktops/assets/127661559/027c74d6-e88a-4142-b32d-5aaa7c75632c)
@levnikmyskin just noticed the version number was incremented up by one in c04fa1f and we don't have a release for that version, should i keep it as 2.2.1 or put it back to 2.2.0?

**Comment by levnikmyskin** [comment]
there's not an official github release, that's true. But plugin version was incremented, and it is updated in `src/main.cpp`. With the latest changes, we are now at `2.2.2`. So, I would bump it to that version :)

Also, please let's move this discussion to a PR.

Thank you so much as always :heart:

**Comment by wiillou** [comment]
@mjund your issue should be fixed now, just update your flake :)

**Comment by levnikmyskin** [comment]
Hi @mjund, please also provide output logs for the failing build

**Comment by mjund** [comment]
the build didn't fail 

heres the log: 

@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/fhj5nnnhva0jjfqkx49b41mv6xxs98ny-xxr33qnfnnh7fm0pn4ncpr4nsnxqwbsc-source
source root is xxr33qnfnnh7fm0pn4ncpr4nsnxqwbsc-source
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
g++ -O2 -shared -g -fPIC --no-gnu-unique -std=c++23 -Wall -Iinclude -DWLR_USE_UNSTABLE `pkg-config --cflags pixman-1 libdrm hyprland`   src/VirtualDesk.cpp src/VirtualDeskManager.cpp s>
src/VirtualDesk.cpp: In member function 'Layout VirtualDesk::generateCurrentMonitorLayout()':
src/VirtualDesk.cpp:177:41: warning: comparison of integer expressions of different signedness: 'int' and 'long unsigned int' [-Wsign-compare]
  177 |     for (int i = vdeskFirstWorkspace; i < vdeskFirstWorkspace + monitors.size(); i++) {
      |                                       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
buildPhase completed in 2 minutes 42 seconds
@nix { "action": "setPhase", "phase": "glibPreInstallPhase" }
Running phase: glibPreInstallPhase
@nix { "action": "setPhase", "phase": "installPhase" }
Running phase: installPhase
@nix { "action": "setPhase", "phase": "glibPreFixupPhase" }
Running phase: glibPreFixupPhase
@nix { "action": "setPhase", "phase": "fixupPhase" }
Running phase: fixupPhase
shrinking RPATHs of ELF executables and libraries in /nix/store/bv1w6isfjknb853hnf9adhw22b48i36g-virtual-desktops-2.2.2
shrinking /nix/store/bv1w6isfjknb853hnf9adhw22b48i36g-virtual-desktops-2.2.2/lib/libvirtual-desktops.so
checking for references to /build/ in /nix/store/bv1w6isfjknb853hnf9adhw22b48i36g-virtual-desktops-2.2.2...
patching script interpreter paths in /nix/store/bv1w6isfjknb853hnf9adhw22b48i36g-virtual-desktops-2.2.2
stripping (with command strip and flags -S -p) in  /nix/store/bv1w6isfjknb853hnf9adhw22b48i36g-virtual-desktops-2.2.2/lib
...skipping...
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/fhj5nnnhva0jjfqkx49b41mv6xxs98ny-xxr33qnfnnh7fm0pn4ncpr4nsnxqwbsc-source
source root is xxr33qnfnnh7fm0pn4ncpr4nsnxqwbsc-source
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
g++ -O2 -shared -g -fPIC --no-gnu-unique -std=c++23 -Wall -Iinclude -DWLR_USE_UNSTABLE `pkg-config --cflags pixman-1 libdrm hyprland`   src/VirtualDesk.cpp src/VirtualDeskManager.cpp s>
src/VirtualDesk.cpp: In member function 'Layout VirtualDesk::generateCurrentMonitorLayout()':
src/VirtualDesk.cpp:177:41: warning: comparison of integer expressions of different signedness: 'int' and 'long unsigned int' [-Wsign-compare]
  177 |     for (int i = vdeskFirstWorkspace; i < vdeskFirstWorkspace + monitors.size(); i++) {
      |                                       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
buildPhase completed in 2 minutes 42 seconds
@nix { "action": "setPhase", "phase": "glibPreInstallPhase" }
Running phase: glibPreInstallPhase
@nix { "action": "setPhase", "phase": "installPhase" }
Running phase: installPhase
@nix { "action": "setPhase", "phase": "glibPreFixupPhase" }
Running phase: glibPreFixupPhase
@nix { "action": "setPhase", "phase": "fixupPhase" }
Running phase: fixupPhase
shrinking RPATHs of ELF executables and libraries in /nix/store/bv1w6isfjknb853hnf9adhw22b48i36g-virtual-desktops-2.2.2
shrinking /nix/store/bv1w6isfjknb853hnf9adhw22b48i36g-virtual-desktops-2.2.2/lib/libvirtual-desktops.so
checking for references to /build/ in /nix/store/bv1w6isfjknb853hnf9adhw22b48i36g-virtual-desktops-2.2.2...
patching script interpreter paths in /nix/store/bv1w6isfjknb853hnf9adhw22b48i36g-virtual-desktops-2.2.2
stripping (with command strip and flags -S -p) in  /nix/store/bv1w6isfjknb853hnf9adhw22b48i36g-virtual-desktops-2.2.2/lib

but the plugin doesn't load. i don't know if the problem from hyprland or the plugin

**Comment by wiillou** [comment]
can i see your flake please? @mjund

**Comment by mjund** [comment]
i ll try to install it on aonther machine

**Comment by mjund** [comment]
@wiillou sure.

the flake:
https://github.com/mjund/xon/blob/main/flake.nix

hyprland:
https://github.com/mjund/xon/blob/main/gui/hyprland/default.nix

diagram to show the structure of the flake for hyprland

![x](https://github.com/levnikmyskin/hyprland-virtual-desktops/assets/116303766/c9f55f05-c550-4735-883d-0742531f7050)

**Comment by wiillou** [comment]
> @wiillou sure.
> 
> the flake: https://github.com/mjund/xon/blob/main/flake.nix
> 
> hyprland: https://github.com/mjund/xon/blob/main/gui/hyprland/default.nix
> 
> diagram to show the structure of the flake for hyprland
> 
> ![x](https://private-user-images.githubusercontent.com/116303766/328271423-c9f55f05-c550-4735-883d-0742531f7050.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTg1ODMsIm5iZiI6MTcxNTAxODI4MywicGF0aCI6Ii8xMTYzMDM3NjYvMzI4MjcxNDIzLWM5ZjU1ZjA1LWM1NTAtNDczNS04ODNkLTA3NDI1MzFmNzA1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxNzU4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MmE0YTAzZGE2NTAxMjllYzFmNDAwNzY3M2RmOGJmOWRkZmNjYjNmY2RmMjViM2UyYzVmMDNiZmNmODBjMDA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f126R28Xqd5V6L1YLegHXGhgTFCh39FgHdEqxpBJQ-A)

change your hyprland.url to "git+https://github.com/hyprwm/Hyprland?submodules=1"

**Comment by levnikmyskin** [comment]
@mjund was this fixed? I'd close this issue if we can

**Comment by mjund** [comment]
> @mjund change your hyprland.url to "git+https://github.com/hyprwm/Hyprland?submodules=1" and then run a `nix flake update`

This fixed the issue. but I ran into another problem. I think the problem from either hyprland or from my system basically whenever I try to use some hyprctl commands including the plugin's commands hyprctl can't connect to the socket. 

This ticket is regarding installing the plugin for nixOS which we solve the problem. @levnikmyskin feel free to close the issue. I'll comment on how I solved the socket problem whenever I solve it for anyone might go into the same problem as me. 

@wiillou thanks for your help solving the issue and your contribution. @levnikmyskin thanks for the great plugin

**Comment by wiillou** [comment]
>  but I ran into another problem. I think the problem from either hyprland or from my system basically whenever I try to use some hyprctl commands (including the plugin's commands) hyprctl can't connect to the socket.
@mjund 
It's due to an update to hyprland where they changed the socket location. Should go away when you restart.

**Comment by levnikmyskin** [comment]
Nice,good that this was solved
