### ISSUE TITLE
confused about `lastdesk` dispatcher

### ISSUE THREAD

**Issue by gitacrobat** [levnikmyskin/hyprland-virtual-desktops#30]
I would like to cycle back to the last visited virtual desk via Mod+Tab like with hyprland workspaces `workspace previous`.
I set it up with `bind = $mainMod, TAB, vdesk, lastdesk`.

So if I change from vdesk 3 to vdesk 8 via the `vdesk 3` and `vdesk 8` dispatchers Mod+Tab should take me back to vdesk 3. I have three screens set up. But instead it always takes me to workspaces 28/29/30.

I'm not sure what is wrong with my setup.

**Comment by levnikmyskin** [comment]
Hi, `lastdesk` is its own dispatcher, you don't need to mix it with vdesk. 
Change your binding to:  
`bind = $mainMod, TAB, lastdesk`

Let me know if it works, and I'll close this issue

**Comment by gitacrobat** [comment]
Thank you very much. The documentation is clear enough but I somehow managed to misread it. Closing the issue.
