### ISSUE TITLE
[Request] Support for `hyprpm` plugin manager

### ISSUE THREAD

**Issue by Kage-Yami** [levnikmyskin/hyprland-virtual-desktops#5]
Looks like Hyprland has a native plugin manager, `hyprpm`, mentioned here: https://wiki.hyprland.org/Plugins/Using-Plugins/#installing--using-plugins

Would be nice if this plugin supported that. :)

The official plugins repo has an example manifest for `hyprpm`: https://github.com/hyprwm/hyprland-plugins/blob/main/hyprpm.toml

**Comment by levnikmyskin** [comment]
Hi! 
That looks pretty cool, and very new! As far as I can see, hyprpm was added just a few days ago to Hyprland. 
I've started a [WIP branch](https://github.com/levnikmyskin/hyprland-virtual-desktops/tree/feat/hyprpm), but I'll only test it and merge it once hyprpm is released in one of Hyprland's official releases :)

**Comment by vaxerski** [comment]
fwiw hyprpm is a part of hyprland now since 0.33

**Comment by levnikmyskin** [comment]
hey Vaxry, thanks for the heads up :) I noticed and I wanted to release the integration already, but I'm taking life (and work outside of my job) much slower these weeks.  
That said, I was planning to implement and test hyprpm integration in the weekend.  

Ps. this hyprpm thing is pretty cool btw, keep up the good work on Hyprland :)

**Comment by levnikmyskin** [comment]
This is now implemented and merged in main
