### ISSUE TITLE
NixOS Help

### ISSUE THREAD

**Issue by milesje** [levnikmyskin/hyprland-virtual-desktops#6]
I'm attempting to get this plugin to work via NixOS Flakes... any insight into getting this working....

Here is a link to the [WIki](https://nixos.wiki/wiki/Hyprland#Plugin) page that has instructions on using plugins with NixOS Flakes.

**Comment by levnikmyskin** [comment]
Hey! Unfortunately I have no idea about NixOS or Nix at all. If you figure it out, feel welcome to open a PR :)

**Comment by milesje** [comment]
Thanks I'm working on it.. I forked the project and will work on the Nix integration... when (if) I get it working I will do a PR!

**Comment by levnikmyskin** [comment]
Sounds good, good luck with it! Also, I checked the forks of this project and there seems to be another one trying to do the same thing...maybe you could check that out (from mobile, so difficult to link it)

**Comment by milesje** [comment]
@levnikmyskin do you have a link to the other fork? For some reason GitHub doesn't show me the other forks and when I search all I'm finding is your repo.

**Comment by mjund** [comment]
any updates on this? did you manage to get it working with flakes?

**Comment by levnikmyskin** [comment]
Do you still need this after the latest release? If you manage the plugin with hyprpm, you don't need this am I right?

**Comment by SamueleFacenda** [comment]
Hello, [this](https://github.com/SamueleFacenda/nixos-config/blob/main/packages/hyprland-virtual-desktops.nix) is the package in my config, it works if you put it in the `plugins` field of home-manager's hyprland settings. Pay attention to [this line](https://github.com/SamueleFacenda/nixos-config/blob/f1b18170f42bfcd767868d162723ead1067e28e8/overlays/new-packages.nix#L15), the package is added via an overlay to nixpkgs and uses the hyprland flake output for the build.

Instead of copying the package source to your config you can just reference my flake as input and override the hyprland 
flake (as described in the nixos wiki linked above), but I don't guarantee to mantain the package up to date.

**Comment by Serpentian** [comment]
> Do you still need this after the latest release? If you manage the plugin with hyprpm, you don't need this am I right?

Using hyprpm is against declarative configuration of NixOS. We still need it in the repo.
https://github.com/hyprwm/Hyprland/issues/4664#issuecomment-1937009147

**Comment by levnikmyskin** [comment]
I see. Unfortunately I have no idea how nix works, so cannot really help you with this guys :/

**Comment by wiillou** [comment]
Hello, i believe i have managed to get this working, i will make a pull request when i have some time (so later today)

**Comment by levnikmyskin** [comment]
Sounds amazing! In the meantime, I've just started exploring nixos in the past few days, so this is great news. Who knows if I'll switch from arch after 8 years :P

**Comment by wiillou** [comment]
okay, currently it builds a .so file that is definitely not right, it is way too small. i think its not using all the files but i should be able to fix that

**Comment by levnikmyskin** [comment]
If you need any help, feel free to contact me on telegram @Levnikmyskin

**Comment by levnikmyskin** [comment]
ps. I'm about to release version 2.2, but I think it's fine if we merge your nix thing after that (I guess people don't really care about releases on a hyprland plugin anyways)

**Comment by wiillou** [comment]
all you need to to with nix is update the version anyway, so it shouldn't be much of an issue
